version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - Attributify
  - autocorrect
  - bumpp
  - bytea
  - crossws
  - culori
  - deditor
  - defu
  - Elysia
  - elysiajs
  - eslintcache
  - Eventa
  - formkit
  - gramsearch
  - groupultra
  - guiiai
  - hahaqwq
  - henrygd
  - hnsw
  - iconify
  - jieba
  - listhen
  - Logg
  - lucide
  - luoling
  - Megagroups
  - moeru
  - mtproxy
  - nprogress
  - ofetch
  - oklch
  - ollama
  - onnotice
  - overscan
  - pathe
  - pglite
  - pgvector
  - pinia
  - reconnections
  - reka
  - Retriable
  - rolldown
  - shadcn
  - sonner
  - taze
  - tiktoken
  - trpc
  - tsdown
  - tsquery
  - tsvector
  - unbird
  - unocss
  - unplugin
  - uuidv4
  - valibot
  - vectorlite
  - virtua
  - vite
  - vitest
  - vueuse
  - xsai
  - xsschema
ignoreWords: []
import: []
